# See https://docs.redoc.ly/cli/configuration/ for more information.
apis:
  core:
    root: "openapi/openapi.yaml"
plugins:
  - './plugins/local.js'
extends:
  - recommended
rules:
  tag-description: off
preprocessors:
  local/merge-schemas: on
theme:
  openapi:
    showConsole: true
    layout:
      scope: section
    routingStrategy: browser
    htmlTemplate: ./web/index.html
